Remove govet test
metal3-io/project-infra pull request #176
Opened 2021-03-29 08:18 UTC by elfosardo

It's included in golint in PR https://github.com/metal3-io/baremetal-operator/pull/825

2021-03-29 08:19 UTC, elfosardo commented
/assign @fmuyassarov @dhellmann

2021-03-29 08:19 UTC, elfosardo commented
after the 2 PRs merge, we can remove also the scripts from hack in baremetal-operator

2021-03-29 08:55 UTC, fmuyassarov requested changes

2021-03-29 08:55 UTC, fmuyassarov commented on prow/config/config.yaml
> -        imagePullPolicy: Always
This is CAPM3 repo, you need to remove govet from https://github.com/metal3-io/project-infra/blob/ebe2d90c26bb3bf284fd34c2c171a82058249da6/prow/config/config.yaml#L252-L265.

2021-03-29 09:23 UTC, fmuyassarov reviewed
/hold 
until https://github.com/metal3-io/baremetal-operator/pull/825 gets merged.

2021-03-29 09:23 UTC, fmuyassarov commented
/approve

2021-03-29 09:26 UTC, fmuyassarov commented
> /approve

Seems I don't rights here. 
@maelk Would you mind to approve/lgtm this if looks okay?

2021-03-30 06:20 UTC, maelk approved these changes

2021-04-13 08:14 UTC, elfosardo commented
/unhold

2021-04-13 08:15 UTC, elfosardo commented
https://github.com/metal3-io/baremetal-operator/pull/825 merged, this should be good to go

2021-04-13 18:14 UTC, dhellmann commented
/lgtm

2021-04-13 22:28 UTC, fmuyassarov reviewed
/lgtm

2021-04-13 22:29 UTC, merged