Re-configure label synchronization CronJob
metal3-io/project-infra pull request #274
Opened 2021-11-14 06:56 UTC by fmuyassarov

This patch moves label synchronization CronJob to default
namespace, thus updates the Makefile entry related to it.
Also, it makes it to reuse the existing github-token Secret,
and bumps the label synchronization image to
[v20211111-bce61c7c4a]( gcr.io/k8s-prow/label_sync:v20211111-bce61c7c4a).

2021-11-14 06:58 UTC, fmuyassarov commented
/cc @furkatgofurov7 @kashifest

2021-11-15 08:17 UTC, kashifest commented
/approve
Do we need 5 commits or squashing them would be a good idea?

2021-11-15 08:18 UTC, smoshiur1237 approved these changes
LGTM

2021-11-15 15:21 UTC, fmuyassarov commented
> /approve Do we need 5 commits or squashing them would be a good idea?

done

2021-11-15 15:21 UTC, fmuyassarov commented
/cc @furkatgofurov7

2021-11-15 15:26 UTC, furkatgofurov7 requested changes

2021-11-15 15:26 UTC, furkatgofurov7 commented on prow/Makefile
> +	kubectl create configmap label-config --from-file=labels.yaml=labels.yaml --dry-run=client -o yaml | kubectl replace configmap label-config -f -
this should be:
```suggestion
	kubectl create configmap label-config --from-file=labels.yaml=config/labels.yaml --dry-run=client -o yaml | kubectl replace configmap label-config -f -
```
?

2021-11-15 15:51 UTC, fmuyassarov commented on prow/Makefile
> +	kubectl create configmap label-config --from-file=labels.yaml=labels.yaml --dry-run=client -o yaml | kubectl replace configmap label-config -f -
ops, good catch

2021-11-15 15:51 UTC, fmuyassarov commented on prow/Makefile
> +	kubectl create configmap label-config --from-file=labels.yaml=labels.yaml --dry-run=client -o yaml | kubectl replace configmap label-config -f -
@furkatgofurov7 thank you, fixed it.

2021-11-16 08:00 UTC, furkatgofurov7 reviewed
/lgtm

2021-11-16 08:01 UTC, merged