Change the BML to use node 5 as a provisioned node
metal3-io/project-infra pull request #343
Opened 2022-02-09 15:48 UTC by namnx228

Since the node 4 of BML is facing a hardware issue that blocks it from turning on, using node 5 is a workaround.

2022-02-09 15:49 UTC, namnx228 commented
/assign @furkatgofurov7 
/cc @macaptain

2022-02-09 15:51 UTC, macaptain requested changes

2022-02-09 15:51 UTC, macaptain commented on jenkins/scripts/bare_metal_lab/templates/bmhosts_crs.yaml.j2
>      address: ilo4://192.168.1.13
The address of the BMC needs updating as well to match the host.

2022-02-09 15:51 UTC, macaptain commented on jenkins/scripts/bare_metal_lab/templates/bmhosts_crs.yaml.j2
>    bootMACAddress: 80:c1:6e:7a:e8:10
And also the MAC address!

2022-02-10 09:00 UTC, macaptain commented
/test-integration-bml-centos

2022-02-10 15:53 UTC, namnx228 commented
/test-integration-bml-centos

2022-02-11 08:04 UTC, lentzi90 approved these changes

2022-02-11 08:05 UTC, kashifest commented
/retitle Change the BML to use node 6 as a provisioned node

2022-02-11 08:05 UTC, furkatgofurov7 reviewed
/lgtm

2022-02-11 08:07 UTC, merged