WIP: add KUBECTL_SHA256 passthru from JJB
metal3-io/project-infra pull request #575
Opened 2023-09-04 09:51 UTC by tuminoid

We need to pass `KUBECTL_SHA256` matching `KUBERNETES_VERSION` or `KUBERNETES_VERSION_UPGRADE_FROM` version from JJB, depending on the test.

In this WIP version, we test the passthru by passing invalid values, which should be visible in the failing test output.

Depends on https://github.com/metal3-io/cluster-api-provider-metal3/pull/1178 and https://github.com/metal3-io/metal3-dev-env/pull/1289 to been merged first.

2023-09-04 09:51 UTC, tuminoid commented
This should not fail, since capm3 PR is not merged yet, but let's see.

/test-ubuntu-integration-main

2023-09-04 09:55 UTC, tuminoid commented
/test-ubuntu-integration-main

2023-09-04 09:56 UTC, tuminoid commented
/test-ubuntu-integration-main

2023-09-04 12:05 UTC, tuminoid commented
/test-centos-e2e-integration-main

This e2e should fail with an error message specified in this PR as fake digest.

2023-09-04 12:10 UTC, tuminoid commented
> /test-centos-e2e-integration-main
> 
> This e2e should fail with an error message specified in this PR as fake digest.

Actually it should not, since the versions match, the digest isn't actually going to be checked.

/test-e2e-upgrade-main-from-release-0-5
/test-e2e-upgrade-main-from-release-1-4

2023-09-04 12:39 UTC, tuminoid commented
/test-e2e-1-24-1-25-upgrade-main

2023-09-04 12:57 UTC, tuminoid commented
/test-e2e-1-24-1-25-upgrade-main

2023-09-04 13:19 UTC, tuminoid commented
```console
fatal: https://storage.googleapis.com/kubernetes-release/release/v1.25.5/bin/linux/amd64/kubectl binary checksum '6a660cd44db3d4bfe1563f6689cbe2ffb28ee4baf3532e04fff2d7b909081c29' differs from expected checksum 'this-was-defined-in-integration-test-script'
```

All checks out, should be fine to pass thru from JJB.

2023-09-04 13:21 UTC, tuminoid commented
/test-ubuntu-integration-main 

/hold
I'll add the SHA digests into JJB first, so we can test the passthru.

2023-09-05 09:27 UTC, tuminoid commented
/test-e2e-1-25-1-26-upgrade-main

2023-09-05 10:49 UTC, tuminoid commented
One more JJB change needed, waiting that.

2023-09-05 11:51 UTC, tuminoid commented
/test-e2e-1-25-1-26-upgrade-main

2023-09-05 12:35 UTC, tuminoid commented
/test-e2e-1-25-1-26-upgrade-main

2023-09-05 12:39 UTC, tuminoid commented
/test-e2e-1-24-1-25-upgrade-main

2023-09-05 12:44 UTC, tuminoid commented
/unhold

Upgrade tests have passed the part wherre it checks for kubectl sha, so it is going to work.

2023-09-05 12:50 UTC, lentzi90 reviewed
/approve
Thanks for the thorough tests and explanations, really helpful when reviewing!

2023-09-05 12:52 UTC, tuminoid commented
/test-ubuntu-integration-main  

Fixed WIP in git commit title, and removed one placeholder text.

2023-09-05 12:54 UTC, kashifest requested changes

2023-09-05 12:54 UTC, kashifest commented on jenkins/scripts/files/run_integration_tests.sh
> +    export KUBECTL_SHA256="${KUBECTL_SHA256:-}"
```suggestion
    export KUBECTL_SHA256="${KUBECTL_SHA256}"
```

2023-09-05 12:59 UTC, tuminoid commented
/test-ubuntu-integration-main
/cc @kashifest

2023-09-05 13:07 UTC, tuminoid commented
/test-e2e-1-25-1-26-upgrade-main
/test-e2e-1-26-1-27-upgrade-main
/test-e2e-1-27-1-28-upgrade-main

Let's make sure the last change didn't affect these. They're good if they pass the kubectl sha verification, even if they fail later.

2023-09-05 13:25 UTC, kashifest approved these changes
/lgtm

2023-09-05 14:36 UTC, tuminoid commented
/test-ubuntu-integration-main
Db locked flake.

2023-09-05 15:21 UTC, merged